version: '3.8'

services:
  bot:
    image: currencyratebalebot:0.1.0
    container_name: currency_rate_bale_bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
